import{clamp,sleep,median,dp,ridge}from'./math.js';
import{FaceTracker}from'./tracker.js';

const $=id=>document.getElementById(id),video=$('video'),status=$('status'),diag=$('diag'),cam=$('cam'),calBtn=$('calBtn'),blinkCalBtn=$('blinkCalBtn'),controlBtn=$('controlBtn'),scrollBtn=$('scrollBtn'),assist=$('assist'),pace=$('pace'),cursor=$('cursor'),cal=$('cal'),dotEl=$('dot'),ct=$('ct'),ch=$('ch'),rest=$('rest'),calProgress=$('calProgress'),toast=$('toast');
const tracker=new FaceTracker();
let running=false,calibrated=false,latest=null,latestAt=0,modelX=null,modelY=null,lastInfer=0,frames=0,fpsAt=performance.now(),toastTimer=null;
let sx=innerWidth/2,sy=innerHeight/2,lastTargetX=sx,lastTargetY=sy,lastStablePoint={x:sx,y:sy,at:0,velocity:999},focusEl=null,clicks=0;
let controlState='off',frozenClickPoint=null,leftWinkAt=0,leftWinkLatched=false,rightWinkAt=0,rightWinkLatched=false;
let bothClosed=false,blinkStart=0,blinkSymSum=0,blinkSymN=0,previousBlink=null,blinkProfile=null,blinkCalActive=false,blinkTrialResolve=null;
let scrollZone='center',scrollZoneSince=0,lastScrollAt=0;
const FOLLOW_LAG_MS=180,MOTION_WARMUP_MS=500;
const PATHS=[{a:[.08,.10],b:[.92,.10],kind:'h'},{a:[.92,.30],b:[.08,.30],kind:'h'},{a:[.08,.50],b:[.92,.50],kind:'h'},{a:[.92,.70],b:[.08,.70],kind:'h'},{a:[.08,.90],b:[.92,.90],kind:'h'},{a:[.20,.10],b:[.20,.90],kind:'v'},{a:[.50,.90],b:[.50,.10],kind:'v'},{a:[.80,.10],b:[.80,.90],kind:'v'}];

function st(t,c=''){status.textContent=t;status.className='pill'+(c?' '+c:'')}
function msg(t,ms=2400){toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),ms)}
function clearFocus(){if(focusEl){focusEl.classList.remove('focus');focusEl=null}}
function setControlState(next,announce=true){controlState=next;const off=next==='off',scroll=next==='scroll';$('controlTag').textContent='Control: '+(off?'OFF':scroll?'SCROLL':'POINTER');controlBtn.textContent=off?'Eye control OFF':'Eye control ON';scrollBtn.textContent=scroll?'Scroll mode':'Pointer mode';scrollBtn.disabled=off||!calibrated;if(off){cursor.style.display='none';clearFocus();scrollZone='center'}if(announce)msg(off?'Eye control off':scroll?'Scroll mode':'Pointer mode',1200)}
function toggleControl(){if(!calibrated)return msg('Calibrate gaze first.');setControlState(controlState==='off'?'pointer':'off')}
function toggleScroll(){if(controlState!=='off')setControlState(controlState==='scroll'?'pointer':'scroll')}
function calibrationFrameOK(){return latest&&performance.now()-latestAt<120&&latest.blink.l<.86&&latest.blink.r<.86}
function snapTarget(x,y,velocity){if(!assist.checked||velocity>15)return{x,y,el:null};const els=[...document.querySelectorAll('.letter,button:not(:disabled),select')];let best=null,bd=30;for(const el of els){const r=el.getBoundingClientRect();if(!r.width||!r.height)continue;const cx=r.left+r.width/2,cy=r.top+r.height/2,d=Math.hypot(x-cx,y-cy);if(d<bd){bd=d;best={x:cx,y:cy,el}}}return best||{x,y,el:null}}
function smoothCursor(tx,ty){const dx=tx-sx,dy=ty-sy,d=Math.hypot(dx,dy);let alpha=d<18?.07:d<70?.11:d<180?.17:.24,stepx=dx*alpha,stepy=dy*alpha;const step=Math.hypot(stepx,stepy),maxStep=48;if(step>maxStep){const k=maxStep/step;stepx*=k;stepy*=k}sx+=stepx;sy+=stepy;return{x:sx,y:sy,velocity:Math.hypot(sx-lastTargetX,sy-lastTargetY)}}
function robustStats(v){const med=median(v),mad=median(v.map(x=>Math.abs(x-med)))||1;return{med,mad}}
function buildBlinkProfile(t){return{d1:robustStats(t.map(x=>x.d1)),gap:robustStats(t.map(x=>x.gap)),d2:robustStats(t.map(x=>x.d2)),total:robustStats(t.map(x=>x.total)),sym:robustStats(t.map(x=>x.sym))}}
function inProfile(v,s,min,max){return Math.abs(v-s.med)<=clamp(2.6*s.mad,min,max)}
function matchesBlinkProfile(c){return!!blinkProfile&&inProfile(c.d1,blinkProfile.d1,45,150)&&inProfile(c.gap,blinkProfile.gap,45,180)&&inProfile(c.d2,blinkProfile.d2,45,150)&&inProfile(c.total,blinkProfile.total,90,260)&&c.total<900&&c.gap>35}
function clickAt(x,y){clicks++;$('clicks').textContent=clicks;cursor.style.display='none';const e=document.elementFromPoint(x,y);if(controlState!=='off')cursor.style.display='block';const target=e?.closest('button,select,a,[role="button"],input');if(target){if(target.tagName==='SELECT')target.focus();else target.click()}}
function handleBlinkEvent(ev){if(previousBlink){const gap=ev.start-previousBlink.end;if(gap>35&&gap<850){const c={d1:previousBlink.dur,gap,d2:ev.dur,total:ev.end-previousBlink.start,sym:(previousBlink.sym+ev.sym)/2};if(blinkCalActive&&blinkTrialResolve){const r=blinkTrialResolve;blinkTrialResolve=null;previousBlink=null;r(c);return}if(controlState==='pointer'&&calibrated&&matchesBlinkProfile(c)&&frozenClickPoint&&frozenClickPoint.velocity<20&&performance.now()-frozenClickPoint.at<1300){clickAt(frozenClickPoint.x,frozenClickPoint.y);msg('Click',600);previousBlink=null;frozenClickPoint=null;return}}}previousBlink=ev}
function processGestures(now){const b=latest.blink,closed=b.l>.62&&b.r>.62,leftOnly=b.l>.76&&b.r<.34,rightOnly=b.r>.76&&b.l<.34;if(previousBlink&&now-previousBlink.end>950){previousBlink=null;frozenClickPoint=null}if(closed&&!bothClosed){blinkStart=now;blinkSymSum=0;blinkSymN=0;if(!previousBlink||now-previousBlink.end>850)frozenClickPoint={...lastStablePoint}}if(closed){blinkSymSum+=Math.abs(b.l-b.r);blinkSymN++}if(!closed&&bothClosed){const dur=now-blinkStart;if(dur>45&&dur<520)handleBlinkEvent({start:blinkStart,end:now,dur,sym:blinkSymN?blinkSymSum/blinkSymN:0})}bothClosed=closed;if(cal.classList.contains('show'))return;if(leftOnly){if(!leftWinkAt)leftWinkAt=now;if(!leftWinkLatched&&now-leftWinkAt>480){leftWinkLatched=true;toggleControl()}}else{leftWinkAt=0;leftWinkLatched=false}if(rightOnly){if(!rightWinkAt)rightWinkAt=now;if(!rightWinkLatched&&now-rightWinkAt>480&&controlState!=='off'){rightWinkLatched=true;toggleScroll()}}else{rightWinkAt=0;rightWinkLatched=false}}
function handleScroll(y,now){const yn=y/innerHeight,zone=yn<.32?'up':yn>.68?'down':'center';if(zone!==scrollZone){scrollZone=zone;scrollZoneSince=now;return}if(zone==='center'||now-scrollZoneSince<340||now-lastScrollAt<45)return;lastScrollAt=now;const depth=zone==='up'?clamp((.32-yn)/.32,0,1):clamp((yn-.68)/.32,0,1),dy=(zone==='up'?-1:1)*(4+18*depth);window.scrollBy(0,dy)}
function updateCursor(now){const tx=clamp(dp(latest.xF,modelX),.005,.995)*innerWidth,ty=clamp(dp(latest.yF,modelY),.005,.995)*innerHeight,sm=smoothCursor(tx,ty),sn=snapTarget(sm.x,sm.y,sm.velocity);if(sn.el!==focusEl){clearFocus();focusEl=sn.el;if(focusEl?.classList.contains('letter'))focusEl.classList.add('focus')}lastStablePoint={x:sn.x,y:sn.y,at:performance.now(),velocity:sm.velocity};$('stableTag').textContent='Cursor stability: '+Math.round(sm.velocity)+' px';lastTargetX=sm.x;lastTargetY=sm.y;if(controlState==='off'){cursor.style.display='none';clearFocus();return}cursor.style.left=sn.x+'px';cursor.style.top=sn.y+'px';cursor.style.display='block';if(controlState==='scroll')handleScroll(sn.y,now)}

async function initTracker(){try{await tracker.init(t=>diag.textContent=t,n=>$('sourceTag').textContent='Tracker source: '+n);st('Tracker ready','ok');diag.textContent='Tracker ready. Start camera.';if(running)requestAnimationFrame(loop)}catch(e){console.error(e);st('Tracker failed','bad');diag.textContent='Tracker error: '+(e.message||e)}}
async function startCamera(){try{await tracker.startCamera(video);running=true;cam.disabled=true;cam.textContent='Camera active';if(tracker.ready)requestAnimationFrame(loop)}catch(e){diag.textContent='Camera error: '+e.name;msg('Allow camera permission in Chrome.',4000)}}
function loop(now){if(!running||!tracker.ready)return;requestAnimationFrame(loop);if(video.readyState<2||now-lastInfer<34)return;lastInfer=now;try{latest=tracker.detect(video,now);latestAt=performance.now();$('face').textContent=latest?'Yes':'No';if(latest){$('pose').textContent=Math.round(latest.pose.yaw)+'°/'+Math.round(latest.pose.pitch)+'°';st(calibrated?'Tracking':'Face locked','ok');calBtn.disabled=false;blinkCalBtn.disabled=false;controlBtn.disabled=!calibrated;diag.textContent=calibrated?'Gaze is tracking. Actions only happen while Eye control is ON.':'Face found. Run Comfort calibrate.';processGestures(now);if(calibrated&&!cal.classList.contains('show')&&latest.blink.l<.56&&latest.blink.r<.56)updateCursor(now)}else{st('Find my face…');calBtn.disabled=true;blinkCalBtn.disabled=true;controlBtn.disabled=true;scrollBtn.disabled=true;cursor.style.display='none';clearFocus()}}catch(e){console.warn(e)}frames++;if(now-fpsAt>1000){$('fps').textContent=Math.round(frames*1000/(now-fpsAt));frames=0;fpsAt=now}}

function pathDuration(kind){return kind==='v'?(pace.value==='very-slow'?11200:9000):5400}
async function showStartPoint(path,index){dotEl.style.display='block';dotEl.style.left=path.a[0]*100+'%';dotEl.style.top=path.a[1]*100+'%';ct.textContent=`Path ${index+1} of ${PATHS.length}`;ch.textContent='Find the tiny center point first. It stays still before moving.';rest.textContent='The first 500 ms of motion will not be recorded.';await sleep(1450)}
async function practiceSweep(){const p={a:[.12,.50],b:[.88,.50]};ct.textContent='Practice only';ch.textContent='Not recorded. Follow the tiny center naturally.';rest.textContent='Do not anticipate it.';dotEl.style.left=p.a[0]*100+'%';dotEl.style.top='50%';await sleep(1450);const start=performance.now();while(true){const now=performance.now(),t=clamp((now-start)/5400,0,1),e=t*t*(3-2*t);dotEl.style.left=(p.a[0]+(p.b[0]-p.a[0])*e)*100+'%';if(t>=1)break;await sleep(16)}await sleep(800)}
async function runSweep(path,index,samples){await showStartPoint(path,index);const history=[],ms=pathDuration(path.kind),start=performance.now();let lastSample=0,count=0;ct.textContent=`${path.kind==='v'?'Slow vertical':'Horizontal'} path ${index+1} of ${PATHS.length}`;ch.textContent=path.kind==='v'?'Vertical movement is much slower. Let your eyes follow without chasing.':'Use the comfortable horizontal pace.';rest.textContent='Blink normally; closed-eye frames are skipped.';while(true){const now=performance.now(),elapsed=now-start,t=clamp(elapsed/ms,0,1),e=t*t*(3-2*t),x=path.a[0]+(path.b[0]-path.a[0])*e,y=path.a[1]+(path.b[1]-path.a[1])*e;dotEl.style.left=x*100+'%';dotEl.style.top=y*100+'%';history.push({t:now,x,y});while(history.length&&history[0].t<now-900)history.shift();if(elapsed>=MOTION_WARMUP_MS&&now-lastSample>44&&calibrationFrameOK()){const labelTime=now-FOLLOW_LAG_MS;let label=history[0]||{x,y},best=Infinity;for(const h of history){const d=Math.abs(h.t-labelTime);if(d<best){best=d;label=h}}samples.push({xF:[...latest.xF],yF:[...latest.yF],x:label.x,y:label.y});lastSample=now;count++}calProgress.style.width=((index+t)/PATHS.length*100).toFixed(1)+'%';if(t>=1)break;await sleep(16)}const end=performance.now()+700;while(performance.now()<end){if(calibrationFrameOK()&&performance.now()-lastSample>48){samples.push({xF:[...latest.xF],yF:[...latest.yF],x:path.b[0],y:path.b[1]});lastSample=performance.now();count++}await sleep(24)}await sleep(460);return count}
async function calibrateGaze(){if(!latest)return msg('Keep your full face and both eyes visible.');setControlState('off',false);calibrated=false;$('calState').textContent='No';$('err').textContent='—';clearFocus();cursor.style.display='none';calBtn.disabled=true;cal.classList.add('show');calProgress.style.width='0%';dotEl.style.display='block';try{const samples=[];dotEl.style.left='50%';dotEl.style.top='50%';ct.textContent='Settle first';ch.textContent='Look at the tiny center point. Blink and relax.';rest.textContent='Nothing moves for 3 seconds.';await sleep(3000);await practiceSweep();ct.textContent='Recorded calibration starts';ch.textContent='Five horizontal paths, an eye break, then three slower vertical paths.';rest.textContent='No diagonals.';await sleep(1400);for(let i=0;i<PATHS.length;i++){if(i===5){ct.textContent='Eye break';ch.textContent='Blink normally and relax for 2.5 seconds.';rest.textContent='Then three slow vertical paths.';dotEl.style.left='50%';dotEl.style.top='50%';await sleep(2500)}await runSweep(PATHS[i],i,samples);$('sampleTag').textContent=`Gaze calibration: ${i+1}/${PATHS.length} paths · ${samples.length} samples`}if(samples.length<220)throw new Error('too few usable gaze samples');modelX=ridge(samples,'x','xF',.010);modelY=ridge(samples,'y','yF',.012);const errors=[];for(let i=0;i<samples.length;i+=9){const q=samples[i],px=clamp(dp(q.xF,modelX),0,1),py=clamp(dp(q.yF,modelY),0,1);errors.push(Math.hypot((px-q.x)*innerWidth,(py-q.y)*innerHeight))}const med=Math.round(median(errors));$('err').textContent=med+' px';calibrated=true;$('calState').textContent='Yes';sx=lastTargetX=innerWidth/2;sy=lastTargetY=innerHeight/2;lastStablePoint={x:sx,y:sy,at:0,velocity:999};$('sampleTag').textContent=`Gaze calibration: complete · ${samples.length} samples`;controlBtn.disabled=false;setControlState('off',false);diag.textContent=`Gaze calibrated with ${FOLLOW_LAG_MS} ms pursuit-lag compensation. Fit error ${med}px. Eye control remains OFF.`;msg('Gaze calibrated. Train double blink next.',3800)}catch(e){console.error(e);modelX=modelY=null;diag.textContent='Calibration failed: '+(e.message||e);msg('Calibration failed. Keep the phone fixed and retry.',4000)}finally{cal.classList.remove('show');calBtn.disabled=!latest;calProgress.style.width='0%';dotEl.style.display='block'}}

function waitForBlinkTrial(timeoutMs=6500){return new Promise((resolve,reject)=>{let active=true;const handler=v=>{if(!active)return;active=false;clearTimeout(timer);if(blinkTrialResolve===handler)blinkTrialResolve=null;resolve(v)},timer=setTimeout(()=>{if(!active)return;active=false;if(blinkTrialResolve===handler)blinkTrialResolve=null;reject(new Error('timeout'))},timeoutMs);blinkTrialResolve=handler})}
async function calibrateBlink(){if(!latest)return msg('Start camera and keep both eyes visible.');setControlState('off',false);blinkCalActive=true;previousBlink=null;frozenClickPoint=null;blinkCalBtn.disabled=true;cal.classList.add('show');dotEl.style.display='none';calProgress.style.width='0%';const trials=[];try{ct.textContent='Double-blink training';ch.textContent='We will record 10 fast intentional double blinks.';rest.textContent='Training begins in 3 seconds.';await sleep(3000);for(let i=0;i<10;i++){if(i===5){ct.textContent='Eye break';ch.textContent='Relax and blink normally for 3 seconds.';rest.textContent='Five examples left.';await sleep(3000)}let ok=false;while(!ok){ct.textContent=`Double blink ${i+1} of 10`;ch.textContent='Wait for READY, then perform one quick double blink.';rest.textContent='Do not blink early.';await sleep(900);ch.textContent='READY — double blink now';try{const c=await waitForBlinkTrial();if(c.total<1050&&c.gap>35&&c.gap<700&&c.d1>45&&c.d2>45){trials.push(c);ok=true;msg('Recorded',550)}else{rest.textContent='Unusual timing. Repeat this one.';await sleep(700)}}catch{rest.textContent='No clear double blink. Repeat this one.';await sleep(700)}}calProgress.style.width=((i+1)/10*100).toFixed(0)+'%';await sleep(420)}blinkProfile=buildBlinkProfile(trials);$('blinkTag').textContent=`Double blink: trained · ${Math.round(blinkProfile.total.med)} ms`;diag.textContent=`Double blink trained. Median total ${Math.round(blinkProfile.total.med)} ms; median gap ${Math.round(blinkProfile.gap.med)} ms.`;msg('Double blink trained. Eye control is still OFF.',3600)}catch(e){console.error(e);blinkProfile=null;$('blinkTag').textContent='Double blink: untrained';msg('Blink training stopped. Try again.',3000)}finally{blinkCalActive=false;blinkTrialResolve=null;previousBlink=null;bothClosed=false;cal.classList.remove('show');dotEl.style.display='block';calProgress.style.width='0%';blinkCalBtn.disabled=!latest}}

for(const c of'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'){const b=document.createElement('button');b.className='letter';b.textContent=c;b.onclick=()=>msg('Selected '+c,900);$('letters').appendChild(b)}
cam.onclick=startCamera;calBtn.onclick=calibrateGaze;blinkCalBtn.onclick=calibrateBlink;controlBtn.onclick=toggleControl;scrollBtn.onclick=toggleScroll;$('full').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{}};
window.addEventListener('orientationchange',()=>{calibrated=false;modelX=modelY=null;$('calState').textContent='No';$('err').textContent='—';controlBtn.disabled=true;scrollBtn.disabled=true;setControlState('off',false);msg('Orientation changed. Calibrate gaze again.',2800)});
setControlState('off',false);initTracker();
